services:
  - type: web
    name: filipino-emigrant-prediction-api
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON VERSION
        value: 3.12.0
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false